---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-plus-logs
rules:
  # Results API needs to be able to verify incoming auth tokens.
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  # Results API needs to be able to use RBAC to verify user authorization.
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-plus-logs
subjects:
  - kind: ServiceAccount
    name: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-plus-logs
